image: ${REGISTRY_HOST}/beckhoff/docker-ubuntu-cached:latest
stages:
  - build

.build-module: &build-module
  stage: build
  script:
    - apt-get update > /dev/null && apt-get install -y build-essential wget git unzip bc > /dev/null
    - wget -nv --no-check-certificate -O artifacts.zip https://${GITLAB_HOST}/beckhoff/build-kernel/builds/artifacts/${KERNEL_REF}/download?job=${KERNEL_JOB}
    - unzip -q artifacts.zip
    - make KDIR=$(pwd)/kernel-modules/lib/modules/*/build
  artifacts:
    paths:
      - bbapi.ko
      - button/bbapi_button.ko
      - display/bbapi_disp.ko
      - power/bbapi_power.ko
      - sups/bbapi_sups.ko
      - watchdog/bbapi_wdt.ko

build-i386-module:
  <<: *build-module
  variables:
    KERNEL_JOB: 'build-i386-kernel'
    KERNEL_REF: 'stable-rt'
    ARCH: 'i386'

build-x86_64-module:
  <<: *build-module
  variables:
    KERNEL_JOB: 'build-x86_64-kernel'
    KERNEL_REF: 'stable-rt'
    ARCH: 'x86_64'
