.build-example: &build-example
  image: ${REGISTRY_HOST}/beckhoff/docker-ubuntu-cached:latest
  stage: build
  before_script:
    - apk add --update alpine-sdk cmake linux-headers
  script:
    - sed -i "s/define CONFIG_INTERACTIVE 1/define CONFIG_INTERACTIVE 0/" test_config.h
    - sed -i.bak "s/\/\*\* select test device \*\//#include \"config_CX01-CX5020.h\"/" test_config.h
    - make binaries
    - mv ./build/unittest.bin unittest.bin.CX01-CX5020
    - mv test_config.h.bak test_config.h
    - sed -i.bak "s/\/\*\* select test device \*\//#include \"config_CX03-CX5140.h\"/" test_config.h
    - make binaries
    - mv ./build/unittest.bin unittest.bin.CX03-CX5140
    - mv test_config.h.bak test_config.h
    - sed -i.bak "s/\/\*\* select test device \*\//#include \"config_CX05-CX2030.h\"/" test_config.h
    - make binaries
    - mv ./build/unittest.bin unittest.bin.CX05-CX2030
    - mv test_config.h.bak test_config.h
  artifacts:
    paths:
      - ./build/*.bin
      - unittest.bin.*

build-i386-example:
  <<: *build-example
  image: i386/alpine

build-x86_64-example:
  <<: *build-example
  image: alpine
