stages:
  - build
  - test

build-debian:
  image: ${REGISTRY_HOST}/docker-registry/docker:debian-bdpg-0.2-master
  stage: build
  before_script:
    - apt update && apt install -y dkms
  script: bdpg build
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ./debian-release

.build-example: &build-example
  image: ${REGISTRY_HOST}/beckhoff/docker-ubuntu-cached:latest
  stage: build
  before_script:
    - apk add --update alpine-sdk cmake linux-headers
  script:
    - sed -i "s/define CONFIG_INTERACTIVE 1/define CONFIG_INTERACTIVE 0/" test_config.h
    - sed -i.bak "s/\/\*\* select test device \*\//#include \"config_CX01-CX5020.h\"/" test_config.h
    - make binaries
    - mv ./build/unittest.bin unittest.bin.CX01-CX5020
    - mv test_config.h.bak test_config.h
    - sed -i.bak "s/\/\*\* select test device \*\//#include \"config_CX03-CX5140.h\"/" test_config.h
    - make binaries
    - mv ./build/unittest.bin unittest.bin.CX03-CX5140
    - mv test_config.h.bak test_config.h
    - sed -i.bak "s/\/\*\* select test device \*\//#include \"config_CX05-CX2030.h\"/" test_config.h
    - make binaries
    - mv ./build/unittest.bin unittest.bin.CX05-CX2030
    - mv test_config.h.bak test_config.h
  artifacts:
    paths:
      - ./build/*.bin
      - unittest.bin.*

build-i386-example:
  <<: *build-example
  image: i386/alpine

build-x86_64-example:
  <<: *build-example
  image: alpine

.build-module: &build-module
  stage: build
  script:
    - apt-get update > /dev/null && apt-get install -y build-essential wget git unzip bc > /dev/null
    - wget -nv --no-check-certificate -O artifacts.zip https://${GITLAB_HOST}/beckhoff/build-kernel/builds/artifacts/${KERNEL_REF}/download?job=${KERNEL_JOB}
    - unzip -q artifacts.zip
    - make KDIR=$(pwd)/kernel-modules/lib/modules/*/build
  artifacts:
    paths:
      - bbapi.ko
      - button/bbapi_button.ko
      - display/bbapi_display.ko
      - power/bbapi_power.ko
      - sups/bbapi_sups.ko
      - wdt/bbapi_wdt.ko

build-i386-module:
  <<: *build-module
  variables:
    KERNEL_JOB: 'build-i386-kernel'
    KERNEL_REF: 'stable-rt'
    ARCH: 'i386'

build-x86_64-module:
  <<: *build-module
  variables:
    KERNEL_JOB: 'build-x86_64-kernel'
    KERNEL_REF: 'stable-rt'
    ARCH: 'x86_64'

.test: &test
  image: ${REGISTRY_HOST}/beckhoff/test_runner:latest
  stage: test
  script:
    - tar -czf /root/tests.tar.gz ./unittest bbapi.ko */bbapi_*.ko ./build/*.bin unittest.bin.*
    - cd /root
    - ./50_power.sh ${DEVICE_ID}-${DEVICE} 0
    - source ./09_init.sh
    - wget -nv --no-check-certificate -O artifacts.zip https://${GITLAB_HOST}/beckhoff/build-kernel/builds/artifacts/${KERNEL_REF}/download?job=${KERNEL_JOB}
    - unzip -q artifacts.zip && rm artifacts.zip
    - wget -nv --no-check-certificate -O artifacts.zip https://${GITLAB_HOST}/beckhoff/build-alpine/builds/artifacts/${ROOTFS_REF}/download?job=${ROOTFS_JOB}
    - unzip -q artifacts.zip
    - ./30_prepare_test.sh ${DEVICE_ID}-${DEVICE} vmlinuz rootfs.cpio.xz nfs
    - ./50_power.sh ${DEVICE_ID}-${DEVICE} 1
    - ./51_wait.sh ${DEVICE_ID}-${DEVICE} root
    - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ./tests.tar.gz root@${TEST_DEVICE_IP}:~/
    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${TEST_DEVICE_IP} tar -xf ./tests.tar.gz
    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${TEST_DEVICE_IP} ./unittest/load-module.sh
    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@${TEST_DEVICE_IP} ./unittest/test-all.sh .${DEVICE_ID}-${DEVICE}
  after_script:
    - cd /root && ./50_power.sh ${DEVICE_ID}-${DEVICE} 0

test-cx2030:
  <<: *test
  variables:
    DEVICE: 'CX2030'
    DEVICE_ID: 'CX05'
    KERNEL_REF: 'stable-rt'
    KERNEL_JOB: 'build-x86_64-kernel'
    ROOTFS_JOB: 'build-x86_64'
    ROOTFS_REF: 'stable'
  dependencies:
    - build-x86_64-module
    - build-x86_64-example
  tags:
    - CX05-CX2030

test-cx5140:
  <<: *test
  variables:
    DEVICE: 'CX5140'
    DEVICE_ID: 'CX03'
    KERNEL_REF: 'stable-rt'
    KERNEL_JOB: 'build-x86_64-kernel'
    ROOTFS_JOB: 'build-x86_64'
    ROOTFS_REF: 'stable'
  dependencies:
    - build-x86_64-module
    - build-x86_64-example
  tags:
    - CX03-CX5140

test-cx5020:
  <<: *test
  variables:
    DEVICE: 'CX5020'
    DEVICE_ID: 'CX01'
    KERNEL_REF: 'stable-rt'
    KERNEL_JOB: 'build-i386-kernel'
    ROOTFS_JOB: 'build-i386'
    ROOTFS_REF: 'stable'
  dependencies:
    - build-i386-module
    - build-i386-example
  tags:
    - CX01-CX5020
