#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (C) Beckhoff Automation GmbH & Co. KG

set -e
set -u

readonly test_device="${1?Missing <test-device>}"
readonly ssh_cmd="ssh Administrator@${test_device}"

${ssh_cmd} /bin/sh -$- <<- EOF
	# Basic trace message for debugging.
	uname -a

	# Suppress sudo warning messages about our hostname.
	printf '127.0.0.1\t%s\n' "\$(hostname)" | sudo tee -a /etc/hosts

	# We could copy this from the test runner, but this looks even easier.
	curl --url "https://git.beckhoff.dev/api/v4/projects/${CI_PROJECT_ID}/repository/archive?sha=${CI_COMMIT_SHA}" | tar --extract --gunzip

	# Now, build and install our bbapi module on the test device.
	cd "${CI_PROJECT_NAME}-${CI_COMMIT_SHA}-${CI_COMMIT_SHA}"
	make
	make install

	# Basic test if the driver was loaded.
	sudo dmesg | grep --ignore-case bbapi
	ls -lh /dev/bbapi

	# With BBAPI available, we should now be able to run our example. At
	# least a minimal subset of the test cases.
	sed -i "s/define CONFIG_INTERACTIVE 1/define CONFIG_INTERACTIVE 0/" test_config.h
	sed -i "s/\/\*\* select test device \*\//#include \"config_c6015.h\"/" test_config.h
	sed -i "s/#define UNITTEST_DO_COMPARE true/#define UNITTEST_DO_COMPARE false/" unittest.cpp
	make binaries
	sudo ./build/unittest.bin
EOF
